### ISSUE TITLE
Colors look a bit flat

### ISSUE THREAD

**Issue by jvanbaarsen** [jeffkreeftmeijer/appsignal.terminal#1]
As discussed here: https://twitter.com/jvanbaarsen/status/972018484958908416 somehow the colors in terminal look a bit flat. At least a lot flatter then in vim for example.

I'm running OSX terminal with tmux and zsh.

**Screenshot from terminal**
<img width="299" alt="screen shot 2018-03-12 at 11 38 41" src="https://user-images.githubusercontent.com/1362793/37279177-4991e69e-25ea-11e8-96d3-962457c6a774.png">

**Screenshot from vim (Running Dim theme)**
<img width="543" alt="screen shot 2018-03-12 at 11 39 02" src="https://user-images.githubusercontent.com/1362793/37279202-5a8ed7f4-25ea-11e8-8d90-09ca4d061a73.png">

**Theme settings terminal**
<img width="465" alt="screen shot 2018-03-12 at 11 42 19" src="https://user-images.githubusercontent.com/1362793/37279232-7b4e0712-25ea-11e8-8f4d-cba760c820fd.png">
<img width="459" alt="screen shot 2018-03-12 at 11 42 34" src="https://user-images.githubusercontent.com/1362793/37279238-7e3912d2-25ea-11e8-9ca4-dc5957a694da.png">

**Comment by jeffkreeftmeijer** [comment]
![screen shot 2018-03-12 at 12 38 48](https://user-images.githubusercontent.com/43621/37281749-55900a04-25f2-11e8-942d-826928b1291a.png)
![screen shot 2018-03-12 at 12 35 45](https://user-images.githubusercontent.com/43621/37281618-f64d7356-25f1-11e8-873d-361b0967ae2b.png)
![screen shot 2018-03-12 at 12 35 50](https://user-images.githubusercontent.com/43621/37281624-f7fe9626-25f1-11e8-84e3-7dd97a25202c.png)

Since your colors look good in Vim, could you check if turning off the "Use bright colors for bold text" fixes the issue? I think you have some bold text in your PS1.

**Comment by jvanbaarsen** [comment]
Yep, that resolved the issue :-) Thanks!
