### ISSUE TITLE
Linux/Tilix support

### ISSUE THREAD

**Issue by davidystephenson** [jeffkreeftmeijer/appsignal.terminal#2]
Is it possible to get a build supported in any Linux terminals? Tilix for one allows themes to be imported and exported as json, as documented here: https://gnunn1.github.io/tilix-web/manual/themes/

Failing that, would it be possible to get the list of colors in hex code format?

**Comment by jeffkreeftmeijer** [comment]
Hey @davidystephenson,

Here's the list of color codes in hex format: https://github.com/jeffkreeftmeijer/appsignal.terminal/blob/master/appsignal.exs. Please note that the colors are different between Terminal.app and other terminals, as Terminal.app blends the colors together. This helps with making the scheme look good on dark and light backgrounds, but makes it difficult to get a theme for another terminal emulator with the same colors.

I've added an iTerm version of the theme, but the colors for that one are slightly different than the Terminal.app one. I'd prefer to drop it entirely because of that, and I don't use iTerm myself.

**Comment by davidystephenson** [comment]
Thank you for the explanation. Are the hex values for the bright colors available somewhere as well, or can they somehow be interpreted through your brightening transformation?

**Comment by jeffkreeftmeijer** [comment]
@davidystephenson ah, of course. That list is no use at all. Here they are:

```
[
  black: "313F46",
  red: "C31633",
  green: "4CAF50",
  yellow: "EFAA04",
  blue: "0961C4",
  magenta: "8A0C8F",
  cyan: "067D8A",
  white: "B1BFC6",
  bright_black: "4B5960",
  bright_red: "FF5673",
  bright_green: "8CEF90",
  bright_yellow: "FFEA44",
  bright_blue: "49A1FF",
  bright_magenta: "CA4CCF",
  bright_cyan: "46BDCA",
  bright_white: "F2FBFF"
]
``` 

Please let me know if you end up using them for something. :)

**Comment by davidystephenson** [comment]
So I put together two tilix themes:

### Dark
```{
    "background-color": "#313F46",
    "badge-color": "#AC7EA8",
    "bold-color": "#FFFFFF",
    "comment": "",
    "cursor-background-color": "#000000",
    "cursor-foreground-color": "#FFFFFF",
    "foreground-color": "#F2FBFF",
    "highlight-background-color": "#000000",
    "highlight-foreground-color": "#FFFFFF",
    "name": "appsignal.terminal-dark",
    "palette": [
        "#313F46",
        "#C31633",
        "#4CAF4F",
        "#EFAA03",
        "#0961C4",
        "#8A0C8F",
        "#067C8A",
        "#B1BFC6",
        "#4B5960",
        "#FF5673",
        "#8BEF90",
        "#FFE943",
        "#49A1FF",
        "#CA4CCF",
        "#46BCCA",
        "#F2FBFF"
    ],
    "use-badge-color": false,
    "use-bold-color": false,
    "use-cursor-color": false,
    "use-highlight-color": false,
    "use-theme-colors": false
}
```

### Light
```
{
    "background-color": "#F2FBFF",
    "badge-color": "#AC7EA8",
    "bold-color": "#FFFFFF",
    "comment": "",
    "cursor-background-color": "#000000",
    "cursor-foreground-color": "#FFFFFF",
    "foreground-color": "#313F46",
    "highlight-background-color": "#000000",
    "highlight-foreground-color": "#FFFFFF",
    "name": "appsignal.terminal-light",
    "palette": [
        "#313F46",
        "#C31633",
        "#4CAF4F",
        "#EFAA03",
        "#0961C4",
        "#8A0C8F",
        "#067C8A",
        "#B1BFC6",
        "#4B5960",
        "#FF5673",
        "#8BEF90",
        "#FFE943",
        "#49A1FF",
        "#CA4CCF",
        "#46BCCA",
        "#F2FBFF"
    ],
    "use-badge-color": false,
    "use-bold-color": false,
    "use-cursor-color": false,
    "use-highlight-color": false,
    "use-theme-colors": false
}
```

Unfortunately, they don't see to fit that well with my editor, even though I'm using dim. You can see how the line numbers are not really visible:

![Invisible line numbers](https://i.imgur.com/XQ9afqO.png)

A somewhat similar issue can be seen here on my terminal prompt, where the user name is difficult to see:

![Difficult user name](https://i.imgur.com/WVVH0c8.png)

Would you like me submit a PR with these themes? Do you have any advice for improving visibility?

If anyone in the future is curious, my stack is: Ubuntu, zsh, oh-my-zsh (ys theme), tilix, vim (jeff's dim theme)

**Comment by jeffkreeftmeijer** [comment]
That looks like the issue we’re running into with iTerm as well. What you’re seeing in your terminal should be the actual colors, but Terminal.app shifts them around to get to the results you see in the screenshots in the README. From what I found, there’s no way to get two themes with the same color values to output the same in Terminal.app and another terminal, like iTerm.

To get closer to what it looks like in Terminal.app, you’d have to pick the colors as rendered in Terminal.app and use those instead of the values in the color list. If you do, please share the list of colors, so others can make themes inspired by this one for their own terminals too. :)

I’ll be dropping iTerm support from this repository the next time I work on this, as this has the same problems. Since I don’t use anything other than Terminal.app, I’m not accepting a patch to add support for other terminals, as I wouldn’t be able to maintain them. Please start your own project, and I’ll gladly link to it. Also; let me know if there’s any way I can help. :)
